name: Visualize matrix build

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: Image URL
        required: true
        default: matrix-finished.png
      reset_image_url:
        description: Reset Image URL
        required: true
        default: matrix-start.png
      duration:
        description: 'Number of job duration in ms'
        required: true
        default: '1000'

jobs:
  reset-led:
    name: "Reset LEDs"
    runs-on: ${{ github.event.inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Reset image
        env:
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{secrets.PLANETSCALE_SERVICE_TOKEN_NAME}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          PLANETSCALE_ORG: "jonico"
        run: |
          pscale connect octodemo add-job-to-matrix-table --execute "python3 publish-pixels-ps.py --max-x=800 --max-y=600 --job-x=0 --job-y=0 --image-file='${{ github.event.inputs.reset_image_url }}'  --environment=barfoo"
        working-directory: ./images

  matrix:
    name: "Matrix job"
    if: "false"
    runs-on: ${{ github.event.inputs.environment }}
    needs: [reset-led]

    strategy:
      fail-fast: true
      matrix:
          x: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
          y: [1,2,3,4,5,6,7,8,9,10,11,12]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Perform job
        env:
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{secrets.PLANETSCALE_SERVICE_TOKEN_NAME}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          PLANETSCALE_ORG: "jonico"
        run: |
          sleep $((RANDOM%5+5))
          pscale connect octodemo add-job-to-matrix-table --execute "python3 visualize-matrix-build-ps.py --max-x=800 --max-y=600 --job-x='${{matrix.x}}' --job-y='${{matrix.y}}' --max-job-x='${{github.event.inputs.x}}' --max-job-y='${{github.event.inputs.y}}' --duration='${{github.event.inputs.duration}}' --environment=barfoo --image-file='${{ github.event.inputs.image_url }}'"
        working-directory: ./images
